<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>5</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DisplayRotate</AssemblyName>
    <RootNamespace>DisplayRotate</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
